### PR TITLE
feat: build esm with cjs

### PR DESCRIPTION
**Pull request by farfromrefug**
this will make the build a bit slower. But .mjs files will be built alongside js files and packaged with the npm package.

### CODE REVIEW

**Comment by rigor789** [comment]
@farfromrefug I just tested this locally, the build looks fine, however an application that depends on it breaks, as webpack seems to default to the `mjs` file rather than the `js` one:

```
Can't import the named export 'launchEvent' from non EcmaScript module (only default export is available)
```

Seems to be because nativescript itself is not an esm build, and this would be a breaking change. 

I'll try changing the package.json so it doesn't mention the `mjs` build - and in that case you would need to add a webpack alias to resolve to the mjs file.

**Comment by farfromrefug** [comment]
@rigor789 that s weird. N webpack templates do not allow mjs files:
https://github.com/NativeScript/nativescript-dev-webpack/blob/master/templates/webpack.typescript.js#L121

**Comment by rigor789** [comment]
@farfromrefug right, but I think when you are importing an external dependency it doesn't take those into account, and uses the `module` key in `package.json` if set. If I remove the key from the `package.json` the app runs fine - I'll just quickly test if it's possible to resolve to the `mjs` file via an alias.

**Comment by rigor789** [comment]
Update: @farfromrefug and I decided to hold off on the merge, until NativeScript is ESM compatible to avoid accidentally breaking projects with this change!

**Pull request closed without merging**
