### PR TITLE
Fix ObservableArray items in ListView (Fixes #464)

### LINKED ISSUE #464: ListView/RadListView with ObservableArray; [Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got Object.
### Version
2.2.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=b1M71v&v=2](https://play.nativescript.org/?template=play-vue&id=b1M71v&v=2)
### Platform and OS info
Android, NSVue: 2.2.0, Vue: 2.5.17

### Steps to reproduce
Just run the playground link above and view the device logs.

### What is expected?
The console would not display any warnings about prop type checks

### What is actually happening?
The console is showing [Vue warn]: Invalid prop: type check failed for prop "items". Expected Array, got Object.  This happens with both ListView and RadListView components.

---
This should be a simple fix for the vue ListView and RadListView components; the prop type should be Array | ObservableArray since the latter is a class.

### PR DESCRIPTION
**Pull request by DrunkenPoney**
Just a small patch to fix #464.

I changed the `items` prop's type to `Object` and instead added a validator function which ensures `items` is either an `Array` or an `ObservableArray`. I also adapted the `@itemTap` event emitter correspondingly.

**Edit:** I also added a sample for the issue

### CODE REVIEW

**Comment by rigor789** [comment]
@DrunkenPoney Thanks for the PR! 
I think we could use `type: [Array, Object]` in the props declaration, to allow both - but I like the validator approach too, as it's more specifically checking for Array or ObservableArray!

I'm working on the vue 2.6 version, so I will likely release this as part of that, rather than creating a patch release right away.

**Comment by DrunkenPoney** [comment]
@rigor789 Wouldn't it redundant to check for both types (`Array` and `Object`) since an array is also an object?

**Comment by rigor789** [comment]
@DrunkenPoney haven't even thought about that - that's a good point!

**Comment by tralves** [comment]
Well, turns out we do need both. Vue makes that distinction when validating props. This is what I got now:

```
JS: [Vue warn]: Invalid prop: type check failed for prop "items". Expected Object, got Array 
JS: 
JS: found in
JS: 
JS: ---> <ListView>
JS:        <MessageList> at components/MessageList.vue
```

**Pull request merged**
