### PR TITLE
Vue Router corrections

### PR DESCRIPTION
**Pull request by Skyhark-Projects**
Hi,

I separated my pull request into two commits. 

The first one adds the "a" component in order to let the router-link of vue works (easier to navigate).

The second one corrects the bugs of the router-view. 
Now we are able to navigate to a new activity by create a page component. 
Or we can simple use the router-view in order to have an internal navigation into the same activity.

### CODE REVIEW

**Comment by rigor789** [comment]
Thanks for your contribution, I will review the changes when I get the chance, but from a quick glance, I'm not sure about the `a` component, it seems very specific and tied to a button. What if instead we made it into a new directive `v-router-link`, or leave it as a component but allow passing in a child element to be used as a "button":

```
<!-- not sure if we can override the vue-router's router-link but worth looking into -->
<router-link to="/login">
  <Button text="Go To Login"/>
</router-link>
```

This isn't a full review, but what I am trying to do is to extract the repeating logic of mounting and starting the application. This has proven to be more challenging than I initially thought because of the slight differences in the JavaScript runtime on iOS and Android. While I got everything working perfectly on android, iOS turned out to not work at all. (There is a known limitation that prevents running any js code after the app starts - that is outside of the app scope, this prevents promises from resolving for example).

The changes in `platform/nativescript/plugins/router-plugin.js` sort of bring back similar logic that is used elsewhere, can we try and work on making that logic universal and reside in one place? I'm even thinking of extracting it to its very own file, where we can handle different cases as needed. That would let us have cleaner code in the rest of the framework, and only have 1 file to update when the logic needs to change. 

I understand this might be a lot to ask for, and there is absolutely no pressure on you to do this work yourself, just let me know if you are interested in working on this together, or if you want me to take over and implement the changes myself.

**Comment by Skyhark-Projects** [comment]
Hi,

Yeah, the logic of the router plugin is a little bit the same as the navigator. 
But like you said after the app started we cannot execute any code after the start function.

This is why I recreated partially the same code in the router plugin. But in this one, we are first going to push our page to the navigation stack and then start the app. 

It will be easy to rewrite that part to be used in the navigator plugin. But because we are starting the app we also need to check if the root view is a router-page, in which case we will need to show the matched component directly, or if it's a page that maybe contains a router-view, then we will need to show the full page and not the matched router component.

So this is not really the same logic as the navigator plugin who will just show the required component as a new page.

I'm going to check how I can rewrite the code to keep the navigation functions separated of the router plugin.

The "a" tag component is basically a simple button. Maybe we can check how to let the router-link works without any additional "a" tag component. Then we will need to replace the default "div" tag of the router-link to a "button" tag. The main goal of this part is only to let users navigate with the standard navigation-link without any difference compared to the web version.

**Comment by NZX-DeSiGN** [comment]
Hi @rigor789,

I follow your work for a while now and start learning how to make Android Nativescript-Vue apps.
I begin to understand how it works, but your statement on the iOS JS runtime leaves me puzzled.

Promises doesn't work on an iOS nativescript-vue app ? 
Because here's a quote from Nativescript doc: 

> Promises are a part of ECMAScript 6 (the scripting language of which JavaScript is an implementation). Because Promises have been implemented in the two JavaScript engines NativeScript uses—V8 for Android and JavaScriptCore for iOS—Promises are available for use in NativeScript apps. (https://docs.nativescript.org/tutorial/chapter-4)

Thank you for your incredible work !

**Comment by rigor789** [comment]
Hi @NZX-DeSiGN, to clarify the promise issue, Promises do work in nativescript, but in the iOS javascript runtime, after we call `application.start()` we can't execute any more code (in the scope where we called `application.start()`), so any promises that are pending at this point get "lost", and anything after the line is ignored. I can't find the issue describing this in more depth, but if you take a look at the default templates, there is always a comment like this:
```js
/*
Do not place any code after the application has been started as it will not
be executed on iOS.
*/
```

**Comment by Skyhark-Projects** [comment]
Hi,

I still had no time to check and finish the corrections of the vue router. 
But I have some ideas about the answer of why codes are not executed after the start function.

Basically the main function of any native application is a while loop waiting new events and rendering the app. Without this loop your app will just stops running once your main function has been executed. In C++ you have to manage it by your self but in other new languages like swift everything has been managed in the background.

In IOS if you don't use the start function, I could observer that the apps start and stop immediately. So it seems like the start function of vue NativeScript manage this while loop that needs to be present in order to let the app run. If they truly manage this main while loop into the start function it can explain why any code after this function could not be executed.

We need to verify this hypotheses because it's just a deduction of what I could observe. I didn't check their code.

A workaround could be to call the start function on the next tick (with by example `setImmediate( start )`).

**Comment by rigor789** [comment]
The master has evolved a lot since this PR, and the router is being re-done for ns 4.0 so I'll close this.

**Pull request closed without merging**
