### PR TITLE
Allow developers set the default clearHistory and backstackVisible options when the page is mounted in a frame

### PR DESCRIPTION
**Pull request by msaelices**
See #513

### CODE REVIEW

**Comment by msaelices** [comment]
@rigor789 if you are ok with the change, I will adapt the current docs to reflect this change.

**Comment by rigor789** [comment]
I'm not sure if using a dynamic component inside a `<Frame>` is a good idea - but I'm fine with the changes to allow at least specifying the `backstackVisible` and `clearHistory` options.

Maybe it would be better to only expose a single prop, which allows passing any of the navigation options (this will allow future options to be passed as well).

So `<Frame :navigationOptions="{ clearHistory: true, someFutureOption: false }">` would get merged in using `Object.assign({}, this.navigationOptions)`.

What do you think?

**Comment by msaelices** [comment]
@rigor789 I totally agree with you but, when I reviewed the `frame.js` code I realized that there were already some navigation options considered (see [this code fragment](https://github.com/nativescript-vue/nativescript-vue/blob/master/platform/nativescript/runtime/components/frame.js#L11-L25)) so I kept the same approach and I added some more navigation options.

So, If we change the approach we have to decide if:

a) we remove the current `transition` options adding them in the `navigationOptions` prop, which would add a backward incompatible change

b) we add the `navigationOption` but we keep the current transition one, mixing both approaches which is a little confusing but backward compatible.

**Comment by rigor789** [comment]
I'm happy with option a for 2.4.0 since that will be a 6.0 compatible release (will release it today if I manage to finish everything I have planned). I think I will leave this feature out of the current 2.3 (rc) release.

**Pull request merged**
