### PR TITLE
Fix rollup problem not exporting Vue as the default element. So using NS-vue from TS is harder

### PR DESCRIPTION
**Pull request by msaelices**
Probably there is a more elegant issue, but I'm not a roll-up expert.

See #300.

### CODE REVIEW

**Comment by championswimmer** [comment]
errr you can just use `esModuleInterop: true` in your tsconfig.json :D

**Comment by championswimmer** [comment]
here my tsconfig https://github.com/championswimmer/hasgeek_mobile_nsvue/blob/master/tsconfig.json

**Comment by msaelices** [comment]
@championswimmer it does not works for me. I've added these lines:
```
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "importHelpers": true,
```

but when I put this `main.js` code:
```
import Vue from 'nativescript-vue'
import * as views from './views'

import Foo from 'nativescript-foo'
Vue.use(Foo)
```

I receive this error:

```
System.err: Error calling module function 
System.err: TypeError: Cannot read property 'use' of undefined
...
```

**Comment by msaelices** [comment]
@championswimmer BTW, I think the dirty fix is better because is universal. I mean, it does not depend on the webpack config. It will make `import Vue from 'nativescript-vue'` work always. 

CC/ @rigor789

**Pull request merged**
