### PR TITLE
Fixed Testing with the sample application(s)

### PR DESCRIPTION
**Pull request by brysem**
Purpose:
The instructions for https://github.com/nativescript-vue/nativescript-vue/blob/master/CONTRIBUTING.md resulted in non-working sample application making contributing not possible without first fixing things.

Implemenation:
Added back the missing sample-runner, dependencies and changes made for NativeScript 7.*

Testing:
This PR can be tested by cloning the repository and following the instructions from https://github.com/nativescript-vue/nativescript-vue/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by brysem** [comment]
Fixed a merge conflict with master

**Comment by rigor789** [comment]
Thanks for the PR, most of the changes are not required in NS7 - the only piece we can bring back is the sample runner, however I have intentionally removed it, as it wasn't useful at all. With a recent refactor to use the `entry.js` file as the entry, any sample can be tested, just by changing the import in the `entry.js` file - without the need to restart the whole build process (much much faster).

The docs/contribution guide should be updated instead.

To get started with the repo:

1. clone the repository
1. `cd nativescript-vue`
1. `yarn` - to install dependencies
1. `yarn dev` - to build nativescript-vue and nativescript-vue-template-compiler in watch mode
1. `cd samples`
1. `ns run <platform> --no-hmr` (disabling hmr isn't necessary, but preferred most of the time)

To test a different/new sample: 
1. edit `entry.js` and update the `require('./<sample>')` statement to require any of the samples in the `app` folder.

**Comment by jarmani** [comment]
@rigor789 @brysem https://github.com/nativescript-vue/nativescript-vue/pull/751 only update the doc and should replace this one if you are ok with it.

**Comment by rigor789** [comment]
Thanks for the PR, but closing this - as the removal was intentional and #751 addressed the missing documentation.

**Pull request closed without merging**
