### PR TITLE
Add rest of the UI components to the app-with-all-components sample app

### PR DESCRIPTION
**Pull request by msaelices**
See #241 

CC/ @rigor789

### CODE REVIEW

**Comment by msaelices** [comment]
@rigor789 note that your merge action was to the `pr/266` branch, not to master

**Comment by msaelices** [comment]
@rigor789 also, I think after this merge, the breaking change comment in the CHANGELOG is not needed anymore.

**Comment by rigor789** [comment]
Yeah I manually merged from `pr/266` after this merge, I think most of it was duplicated - only merged the `nativeView` getter, and the sample app. Did I miss anything @msaelices ?

**Comment by msaelices** [comment]
@rigor789, I also think the breaking changes section on the 2.0.0 changelog is wrong, as we have the nativeView available on both functional and regular components

**Comment by rigor789** [comment]
@msaelices ah yeah, will remove that, and eventually write an "update guide" when stable is out.

**Pull request merged**
