### PR TITLE
Fix listview cell recycling

### LINKED ISSUE #565: <ListView> is very slow comparing to NS Core
### Version
2.4.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=KhyRrD](https://play.nativescript.org/?template=play-vue&id=KhyRrD)
### Platform and OS info
iOS 12/13, Android 8/9, NS Playground

### Steps to reproduce
Open the playground https://play.nativescript.org/?template=play-vue&id=KhyRrD.

This project has 2 listviews linked to the same dataset. The one on the right is more complex because it uses different `<v-template>` and a `<GridLayout>` for some cells.

Notice that the list view is sluggish, especially the right one.

### What is expected?
The ListView should scroll smoothly.

I created an NS Core project with the same dataset and the same UI here: https://play.nativescript.org/?template=play-tsc&id=KkPYYX.

See how smooth it scrolls!

### What is actually happening?
On NS-Vue, the ListView scroll is very sluggish compared to the NS Core ListView.

I tested on both Android and iOS devices. The same thing happens: NS Core is smooth, NS-Vue is slow.

---
The NS-Vue wrapper is doing something that kills the ListView performance. I will start looking at this issue, but I think I'll need the experts on this one.

### PR DESCRIPTION
**Pull request by tralves**
Fixes #565.

The `<NativeListView>` was not setting the `itemTemplates` property correctly.

I am not sure why it was setting `_itemTemplatesInternal` instead of `itemTemplates` before, but now it works. According to my tests, the cell recycling works properly with multi-templates and the scroll is visibly smoother.

For comparison of a before/after, see the [updated playground app](https://play.nativescript.org/?template=play-vue&id=KhyRrD&v=9). The list on the right is patched with this fix.

### CODE REVIEW

**Comment by tralves** [comment]
On the same note, should we change `_itemTemplateSelector` to `itemTemplateSelector`?

PRed...

**Comment by rigor789** [comment]
I can't recall the exact reason we had to use `_itemTemplatesInternal` - but I do remember having issues with just `itemTemplates` when I implemented the ListView. It has likely been fixed in ns core since then.

**Comment by topclaudy** [comment]
Is this fix released?

**Comment by rigor789** [comment]
@topclaudy yes in an alpha release (it is safe to upgrade - I have been using the latest alpha for a while) https://github.com/nativescript-vue/nativescript-vue/releases/tag/v2.5.0-alpha.2

**Comment by romandragan** [comment]
@rigor789, maybe related.

For us the app is randomly crashing on iOS after showing this in console:

```
[Vue warn]: Error in v-on handler: "TypeError: args.object._itemTemplateSelector is not a function
```

**Pull request merged**
