### PR TITLE
Livesync/HMR fixes with the new (unreleased) NativeScript 6.0 

### PR DESCRIPTION
**Pull request by msaelices**
See #507

### CODE REVIEW

**Comment by msaelices** [comment]
@VladimirAmiorkov actually this branch should not be merged into `master` as it's incompatible with NS5.

We think to know if this branch will be a different non-backward-compatible NS-vue version or should we add conditions and checks to make it work properly in both versions.  

/CC @rigor789

**Comment by VladimirAmiorkov** [comment]
Yes NS 6 brings many breaking changes which is why we are releasing a new major version. To me ti looks like supporting both NS 5 and NS 6 in a single code base is going to be not and easy task but its up to you.

**Comment by msaelices** [comment]
Agreed. I am for maintaining two different branches, but Rigor rules

**Comment by jawa-the-hutt** [comment]
Question on this from a semver point of view as well understanding Rigor will ultimately decide.  If we end up with two version of NS-Vue, one for NS 5 and one for NS 6, would it make sense to have the newer NS 6 compatible branch be a Major version change?  Go to 3.x?

Other thought would be to major both and end up with NS-Vue 5.x and NS-Vue 6.x so that it was pretty clear which versions were compatible with which version of NS core.  However, that is a pretty drastic change in version numbering so it may not really help with clarity.

**Comment by rigor789** [comment]
@msaelices I've just talked to @sis0k0 about the release for 6.0, and the plan is to have a `next` or `6.0` (or similar) branch, with these changes - released as 2.4.0-alpha

For 5.x we will release 2.3.0 stable, without any of the breaking changes, and that will likely be the last release for 5.x (unless we need to release a patch)

@jawa-the-hutt it's a little tricky, because I'm trying to keep the version number somewhat semver friendly, but want to keep it similar to Vue's version. The plan is to release 3.x whenever I rewrite NSVue for Vue 3.x.

I'm not sure if releasing a breaking change in 2.4 would cause issues for people though - we'll have to be a bit careful.

**Pull request merged**
