### PR TITLE
[WIP] feat: upgrade to vue 2.6

### PR DESCRIPTION
**Pull request by rigor789**
This PR brings nativescript-vue up to date with vue 2.6.10.

Updates all dependencies, and pins them to finer control of their versions in the future.

Based on changes in #445 and #486

Some things left to do:
- [X] Include changes from #476 to bundle sample/test apps via webpack and support .vue files
- [ ] Include #481 to add appium/travis setup to tests
- [ ] Include changes from #486 to allow jest+vue-test-utils tests to work with nativescript-vue

### CODE REVIEW

**Comment by rigor789** [comment]
@tralves Please, when you get the chance, can you review my changes? I believe everything is OK - just want to make sure I haven't missed anything / messed something up in the process.

**Comment by rigor789** [comment]
@tralves Have you rebuilt the project? I have tested the new slot syntax (samples/app/445.js) and it was working!

**Comment by tralves** [comment]
I dug a little deeper and found out that it doesn't work when using .vue components. E.g:

App.vue (doesn't work):
```xml
<template>
  <Frame>
    <Page>
      <ActionBar title="Vue 2.6 - v-slot #445" />
      <CurrentUser>
        <template v-slot="scope">
          <Label :text="scope.counter" />
        </template>
      </CurrentUser>
    </Page>
  </Frame>
</template>

<script >
import CurrentUser from "~/components/CurrentUser";

export default {
  components: { CurrentUser }
};
</script>
```

Appjs.js (works!!)
```js
import Vue from 'nativescript-vue';
import CurrentUser from './CurrentUser';

export default Vue.component('Appjs', {
  components: { CurrentUser },
  template: `
      <Page>
        <ActionBar title="Vue 2.6 - v-slot #445" />
        <CurrentUser>
          <template v-slot="scope">
            <Label :text="scope.counter" />
          </template>
        </CurrentUser>
      </Page>
  `
});
```

**Comment by msaelices** [comment]
@rigor789, I've just merged #476 into this branch (see https://github.com/nativescript-vue/nativescript-vue/pull/476). As the #476 PR adds support to have .vue samples, I've also created a new .vue sample which checks the new `v-slot` syntax (see https://github.com/nativescript-vue/nativescript-vue/pull/476/commits/0a98c019c67422fbf678353956250dc68d636e72). I can confirm that this sample is not working right now, so @tralves is right.

**Comment by rigor789** [comment]
@tralves @msaelices Fixed it - the issue was that webpack was using a published version rather than the local version that has been updated to support the v-slot syntax. I've ran the `.vue` sample now - and it is working fine.

**Comment by tralves** [comment]
@rigor789 @msaelices yup! it's working!

**Pull request merged**
