### PR TITLE
Wrap all NS elements with Vue components

### PR DESCRIPTION
**Pull request by msaelices**
See #241.

### CODE REVIEW

**Comment by rigor789** [comment]
Opened a new PR with additional changes @msaelices please check if I missed something in #267

**Comment by msaelices** [comment]
@rigor789, awesome. I’ve read your commits and look great. How could I help you on this? Do you think would be worthy if I complete the sample App with the rest of the components?

**Comment by rigor789** [comment]
@msaelices I tried most of the sample apps in the repo, and all seemed to work fine, except the one where the custom component was named `comment`, which is a reserved (internal) component. I would like to add warnings for such cases, but other than that I believe everything should work.

If you want to, sure add all the elements to the sample app and see if everything works

**Comment by msaelices** [comment]
@rigor789 I think having a single app in which you can manually test the basic behavior of every component would be useful for testing quicker if some refactoring is done. At least until we have CI

**Comment by rigor789** [comment]
Absolutely! If you have the capacity feel free to create one. 

I think creating a TabView, and grouping similar components into a separate TabViewItem would be ideal, but up to you!

**Comment by msaelices** [comment]
@rigor789 one thing I noticed using the PR266 as well as your PR267 is that `this.$refs.elementname.$el` returns undefined and still is `this.$refs.elementname.nativeView`. Probably the functional component pass all its data and the reference is made to the NS element instead.

**Comment by msaelices** [comment]
@rigor789 I think I need to give you more feedback about the latest comment. Let see this commit on my branch: https://github.com/msaelices/nativescript-vue/commit/1b0cbe49e9202859d00fd588f10eac7838ecd578

If you look at this fragment code:
```
mounted() {
    Object.keys(this.$refs).map((key) => {
        console.dir(`this.$refs.${key} ->`)
        console.dir(this.$refs[key])
    })
},
```
The previous code only prints:
```
Android: JS: this.$refs.label1 ->
Android: JS: ==== object dump start ====
Android: JS: 0: ElementNode(nativelabel)
Android: JS: 1: ElementNode(nativelabel)
JS: 2: ElementNode(nativelabel)
Android: JS: ==== object dump end ====
JS: this.$refs.date ->
Android: JS: ==== object dump start ====
JS: 0: ElementNode(nativedatepicker)
Android: JS: 1: ElementNode(nativedatepicker)
Android: JS: 2: ElementNode(nativedatepicker)
JS: ==== object dump end ====
```

No `$el` attribute on those.

**Comment by rigor789** [comment]
Yep, this is correct, functional components don't have an `$el` because they don't have a Vue instance attached to them - they are simply just wrappers. This is not a bad thing though, since they should show up in vue-devtools once connected! We could attach a `nativeView` getter to the Vue prototype as a shortcut for `$el.nativeView` - I'll do that before merging if it's not too difficult, or doesn't cause side effects.

**Comment by msaelices** [comment]
@rigor789 awesome!

**Comment by msaelices** [comment]
@rigor789 I was testing the sample apps on iOS and I also added your suggested getter here: https://github.com/nativescript-vue/nativescript-vue/pull/268/commits/024c17f7fa349df6863104e3c3e37e29c0a8f6c2

I hope you like it.

**Pull request closed without merging**
